import type { TranscriptResult } from "./types";
import { parseProxyPool } from "./proxy-http";

const DEMO_VIDEO_ID = "xRh2sVcNXQ8";
const MAX_PROXY_ATTEMPTS = 5;

const DEMO_TRANSCRIPT = `[00:00] 主持人：今天我们讨论 AI 革命最核心的商业问题：它会创造多大的市场，又会怎样改变软件产业？
[01:18] Mark：这轮变化并不只是模型能力提升。AI 已经借助互联网和云基础设施，拥有几乎即时触达全球用户的分发能力。
[03:42] 主持人：消费者为什么愿意付费？
[04:05] Mark：因为产品能直接替用户节省时间、提高产出，甚至帮助个人赚到更多钱。价值足够明确时，订阅模式会非常自然。
[07:31] Mark：企业市场会并存多种计费方式，包括按 token、按席位、按任务量，以及最终按创造的业务价值计费。
[11:08] 主持人：高昂的 GPU 成本会不会限制市场？
[11:42] Mark：短期供给紧张确实推高成本，但芯片、数据中心和推理软件都在快速改善。单位智能成本下降，反而会释放更多需求。
[15:20] Mark：我们正在看到收入快速上升与单位成本快速下降同时发生，这在新技术平台早期非常典型。
[19:16] 主持人：创业公司与大公司分别有什么机会？
[19:44] Mark：大公司掌握分发和数据，创业公司则能围绕新的工作流重做产品。胜负取决于谁能把模型能力转化为真正的用户价值。
[24:08] Mark：未来十年，消费者 AI、企业软件、云服务和数据中心会形成相互推动的智能经济。商业模式不会只有一种。
[28:32] 主持人：所以万亿美元问题的答案是什么？
[28:48] Mark：关键不是预测单一数字，而是理解成本曲线、需求弹性和价值捕获。智能越便宜、越普及，可被重新设计的行业就越多。`;

export class TranscriptError extends Error {
  constructor(message: string, public readonly code: string) {
    super(message);
    this.name = "TranscriptError";
  }
}

export function parseYouTubeVideoId(input: string): string | null {
  const value = input.trim();
  if (/^[\w-]{11}$/.test(value)) return value;

  try {
    const url = new URL(value);
    const host = url.hostname.replace(/^www\./, "");
    let id: string | null = null;

    if (host === "youtu.be") id = url.pathname.split("/").filter(Boolean)[0] ?? null;
    if (host === "youtube.com" || host.endsWith(".youtube.com")) {
      if (url.pathname === "/watch") id = url.searchParams.get("v");
      if (url.pathname.startsWith("/shorts/") || url.pathname.startsWith("/embed/")) {
        id = url.pathname.split("/").filter(Boolean)[1] ?? null;
      }
    }

    return id && /^[\w-]{11}$/.test(id) ? id : null;
  } catch {
    return null;
  }
}

function extractBalancedJson(source: string, marker: string): unknown | null {
  const markerIndex = source.indexOf(marker);
  if (markerIndex < 0) return null;
  const start = source.indexOf("{", markerIndex + marker.length);
  if (start < 0) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;

  for (let i = start; i < source.length; i += 1) {
    const char = source[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }
    if (char === '"') inString = true;
    else if (char === "{") depth += 1;
    else if (char === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          return JSON.parse(source.slice(start, i + 1));
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  kind?: string;
  name?: { simpleText?: string; runs?: Array<{ text: string }> };
}

interface PlayerResponse {
  videoDetails?: { title?: string };
  captions?: {
    playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] };
  };
  playabilityStatus?: { status?: string; reason?: string };
}

export interface Json3Caption {
  events?: Array<{
    tStartMs?: number;
    segs?: Array<{ utf8?: string }>;
  }>;
}

export function json3ToTranscript(payload: Json3Caption): string {
  return (payload.events ?? [])
    .map((event) => {
      const text = (event.segs ?? []).map((segment) => segment.utf8 ?? "").join("").replace(/\s+/g, " ").trim();
      if (!text) return "";
      const totalSeconds = Math.floor((event.tStartMs ?? 0) / 1000);
      const minutes = Math.floor(totalSeconds / 60).toString().padStart(2, "0");
      const seconds = (totalSeconds % 60).toString().padStart(2, "0");
      return `[${minutes}:${seconds}] ${text}`;
    })
    .filter(Boolean)
    .join("\n");
}

function pickCaptionTrack(tracks: CaptionTrack[]): CaptionTrack {
  const score = (track: CaptionTrack): number => {
    const lang = track.languageCode.toLowerCase();
    const languageScore = lang.startsWith("zh") ? 30 : lang.startsWith("en") ? 20 : 10;
    return languageScore + (track.kind === "asr" ? 0 : 2);
  };
  return [...tracks].sort((a, b) => score(b) - score(a))[0];
}

type YouTubeFetcher = (url: string, headers: HeadersInit) => Promise<Response>;
type YouTubeRequester = (url: string, init: RequestInit) => Promise<Response>;

function encodeVarint(value: number): number[] {
  const bytes: number[] = [];
  let remaining = value;
  while (remaining > 0x7f) {
    bytes.push((remaining & 0x7f) | 0x80);
    remaining >>>= 7;
  }
  bytes.push(remaining);
  return bytes;
}

function utf8Bytes(value: string): number[] {
  return [...new TextEncoder().encode(value)];
}

function base64Bytes(bytes: number[]): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

export function buildTranscriptParams(videoId: string, languageCode: string, isAutoGenerated = false): string {
  const trackKind = isAutoGenerated ? "asr" : "";
  const inner = [
    0x0a, ...encodeVarint(utf8Bytes(trackKind).length), ...utf8Bytes(trackKind),
    0x12, ...encodeVarint(utf8Bytes(languageCode).length), ...utf8Bytes(languageCode),
    0x1a, 0x00,
  ];
  const innerEncoded = encodeURIComponent(base64Bytes(inner));
  const panel = "engagement-panel-searchable-transcript-search-panel";
  const outer = [
    0x0a, ...encodeVarint(utf8Bytes(videoId).length), ...utf8Bytes(videoId),
    0x12, ...encodeVarint(utf8Bytes(innerEncoded).length), ...utf8Bytes(innerEncoded),
    0x18, 0x01,
    0x2a, ...encodeVarint(utf8Bytes(panel).length), ...utf8Bytes(panel),
    0x30, 0x01, 0x38, 0x01, 0x40, 0x01,
  ];
  return base64Bytes(outer);
}

function record(value: unknown): Record<string, unknown> | null {
  return value !== null && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function timestamp(milliseconds: number): string {
  const totalSeconds = Math.floor(milliseconds / 1000);
  return `[${Math.floor(totalSeconds / 60).toString().padStart(2, "0")}:${(totalSeconds % 60).toString().padStart(2, "0")}]`;
}

export function transcriptEndpointToTranscript(payload: unknown): string {
  const lines: string[] = [];
  const seen = new Set<string>();
  const visit = (value: unknown): void => {
    if (Array.isArray(value)) {
      for (const item of value) visit(item);
      return;
    }
    const item = record(value);
    if (!item) return;
    const renderer = record(item.transcriptSegmentRenderer);
    if (renderer) {
      const snippet = record(renderer.snippet);
      const runs = Array.isArray(snippet?.runs) ? snippet.runs : [];
      const runText = runs.map((run) => String(record(run)?.text ?? "")).join("");
      const attributed = record(snippet?.elementsAttributedString)?.content;
      const text = (runText || (typeof attributed === "string" ? attributed : "")).replace(/\s+/g, " ").trim();
      const startMs = Number(renderer.startMs ?? 0);
      const key = `${startMs}:${text}`;
      if (text && !seen.has(key)) {
        seen.add(key);
        lines.push(`${timestamp(Number.isFinite(startMs) ? startMs : 0)} ${text}`);
      }
      return;
    }
    for (const child of Object.values(item)) visit(child);
  };
  visit(payload);
  return lines.join("\n");
}

async function fetchTranscriptEndpoint(
  videoId: string,
  languageCode: string,
  isAutoGenerated: boolean,
  html: string,
  requester?: YouTubeRequester,
): Promise<string> {
  if (!requester) return "";
  const visitorData = /"visitorData":"([^"]+)"/.exec(html)?.[1] ?? "";
  const clientVersion = "19.29.37";
  const response = await requester("https://www.youtube.com/youtubei/v1/get_transcript?prettyPrint=false", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Origin: "https://www.youtube.com",
      "User-Agent": `com.google.android.youtube/${clientVersion} (Linux; U; Android 11) gzip`,
    },
    body: JSON.stringify({
      context: {
        client: {
          hl: languageCode,
          gl: "US",
          clientName: "ANDROID",
          clientVersion,
          androidSdkVersion: 30,
          visitorData,
        },
      },
      params: buildTranscriptParams(videoId, languageCode, isAutoGenerated),
    }),
  });
  if (!response.ok) return "";
  return transcriptEndpointToTranscript(await response.json<unknown>());
}

async function fetchTranscriptWith(
  videoId: string,
  fetcher: YouTubeFetcher,
  source: "youtube" | "youtube-proxy",
  requester?: YouTubeRequester,
  captionFetchers: YouTubeFetcher[] = [fetcher],
): Promise<TranscriptResult> {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=en`;
  const response = await fetcher(watchUrl, {
    "Accept-Language": "en-US,en;q=0.9",
    "User-Agent": "Mozilla/5.0 (compatible; VideoDialogueStudio/1.0)",
  });
  if (!response.ok) throw new TranscriptError("YouTube 页面暂时不可访问。", "YOUTUBE_UNAVAILABLE");

  const html = await response.text();
  const player = (extractBalancedJson(html, "ytInitialPlayerResponse") ?? {}) as PlayerResponse;
  const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  if (!tracks.length) {
    const reason = player.playabilityStatus?.reason;
    throw new TranscriptError(reason || "该视频没有公开字幕，或 YouTube 要求验证码。", "CAPTIONS_UNAVAILABLE");
  }

  const track = pickCaptionTrack(tracks);
  const endpointTranscript = await fetchTranscriptEndpoint(
    videoId,
    track.languageCode,
    track.kind === "asr",
    html,
    requester,
  ).catch(() => "");
  if (endpointTranscript) {
    return {
      videoId,
      title: player.videoDetails?.title || `YouTube 视频 ${videoId}`,
      language: track.languageCode,
      text: endpointTranscript.slice(0, 40_000),
      source,
    };
  }
  const separator = track.baseUrl.includes("?") ? "&" : "?";
  const captionUrl = `${track.baseUrl}${separator}fmt=json3`;
  let transcript = "";
  const captionFailures: string[] = [];
  for (const captionFetcher of captionFetchers) {
    try {
      const captionsResponse = await captionFetcher(captionUrl, {
        "Accept-Language": "en-US,en;q=0.9",
        "User-Agent": "Mozilla/5.0 (compatible; VideoDialogueStudio/1.0)",
      });
      if (!captionsResponse.ok) {
        captionFailures.push(`HTTP ${captionsResponse.status}`);
        continue;
      }
      transcript = json3ToTranscript(await captionsResponse.json<Json3Caption>());
      if (transcript) break;
    } catch {
      captionFailures.push("网络或格式错误");
      // Try the next route: direct timedtext first, then the current proxy.
    }
  }
  if (!transcript) {
    const detail = [...new Set(captionFailures)].join("、");
    throw new TranscriptError(`字幕轨道读取失败或为空${detail ? `（${detail}）` : ""}。`, "CAPTION_FETCH_FAILED");
  }

  return {
    videoId,
    title: player.videoDetails?.title || `YouTube 视频 ${videoId}`,
    language: track.languageCode,
    // Durable Object values are stored separately, but keeping the transcript
    // under ~120 KiB also leaves predictable headroom for UTF-8 content.
    text: transcript.slice(0, 40_000),
    source,
  };
}

const directFetcher: YouTubeFetcher = (url, headers) => fetch(url, {
  headers,
  cf: { cacheTtl: 900, cacheEverything: true },
});
const directRequester: YouTubeRequester = (url, init) => fetch(url, init);

export async function getYouTubeTranscript(input: string, webshareProxyUrls?: string): Promise<TranscriptResult> {
  const videoId = parseYouTubeVideoId(input);
  if (!videoId) throw new TranscriptError("请输入有效的 YouTube 视频链接。", "INVALID_URL");

  try {
    return await fetchTranscriptWith(videoId, directFetcher, "youtube", directRequester);
  } catch (directError) {
    if (webshareProxyUrls) {
      const proxies = parseProxyPool(webshareProxyUrls);
      const start = Math.floor(Math.random() * proxies.length);
      const candidates = [...proxies.slice(start), ...proxies.slice(0, start)]
        .slice(0, MAX_PROXY_ATTEMPTS);
      let lastProxyError: unknown;
      const { webshareProxyFetch } = await import("./proxy");
      for (const proxyUrl of candidates) {
        try {
          const proxyRequester: YouTubeRequester = (url, init) => webshareProxyFetch(url, proxyUrl, {
            method: init.method === "POST" ? "POST" : "GET",
            headers: init.headers,
            body: typeof init.body === "string" ? init.body : undefined,
          });
          const proxyFetcher: YouTubeFetcher = (url, headers) => proxyRequester(url, { headers });
          return await fetchTranscriptWith(
            videoId,
            proxyFetcher,
            "youtube-proxy",
            proxyRequester,
            [directFetcher, proxyFetcher],
          );
        } catch (proxyError) {
          lastProxyError = proxyError;
        }
      }
      if (videoId !== DEMO_VIDEO_ID) {
        const message = lastProxyError instanceof Error ? lastProxyError.message : "代理请求失败。";
        throw new TranscriptError(
          `YouTube 直连被拦截，Webshare 代理池回退也失败（已尝试 ${candidates.length}/${proxies.length}）：${message}`,
          "PROXY_FAILED",
        );
      }
    }
    if (videoId === DEMO_VIDEO_ID) {
      return {
        videoId,
        title: "对话安德森：AI 革命的万亿美金之问",
        language: "zh-CN",
        text: DEMO_TRANSCRIPT,
        source: "demo",
      };
    }
    if (directError instanceof TranscriptError) throw directError;
    throw new TranscriptError("YouTube 字幕获取失败；如遇验证码，请配置 WEBSHARE_PROXY_URLS。", "CAPTIONS_UNAVAILABLE");
  }
}
